### ISSUE TITLE
[Feat] 로그인-홈 액티비티 연결, 홈 프래그먼트 전환

### ISSUE THREAD

**Issue by arinming** [UMC-CherryPick-Android/CherryPick-Android#36]
## 설명
로그인 액티비티와 홈 액티비티를 연결합니다.
뉴스, 키워드, 스크랩, 마이페이지 프래그먼트를 홈 액티비티에서 바텀 네비게이션으로 전환할 수 있도록 구현합니다.

## To-Do List
- [x] 로그인-홈 액티비티 연결
- [x] 키워드, 스크랩 프래그먼트 임의로 생성
- [x] 홈 액티비티의 바텀 네비게이션으로 프래그먼트 전환 구현
